// import type { Metadata } from "next";
import "./globals.css";

import { Afacad } from "next/font/google";
import Navbar from "@/components/Navbar";

export const afacad = Afacad({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "PropsNext Realty",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>PropsNext Realty</title>
        <meta name="description" content="Description" />
      </head>
      <body className={`${afacad.className} antialiased bg-[#F5F7F8]`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
